env:
  environment: "LunarLander-v3"
  gravity: -9.81
  enable_wind: 'True'
  obs: '[float, float, float, float, float, float, bool, bool]'
  obs_dim: 8
  action_dim: 4

train:
  device: 'cuda:0'
  n_episodes: 10_000
  optimize:
    optimizer: "SGD"
    learning_rate: 0.01

agent:
  start_epsilon: 1.0
  final_epsilon: 0.1
  epsilon_decay: "linear"
  discount_factor: 0.95